name: DevOps Demo CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Backend Build and Test
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    
    - name: Install Backend Dependencies
      run: |
        cd backend
        npm install
    
    # Docker Build and Push
    - name: Build Docker Image
      run: |
        docker build -t backend-service ./backend
        
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    
    # Deploy to ECS
    - name: Deploy to Amazon ECS
      run: |
        aws ecs update-service --cluster devops-demo-cluster \
        --service backend-service \
        --force-new-deployment